Remove mommy-spatial-generators dependency
It apparently hasn't kept up with model_mommy because it raises an
exception when importing something from model_mommy which is no longer
present:

    from model_mommy.generators import gen_integer

leads to:

    ImportError: cannot import name gen_integer

This is because model_mommy.__init__ used to import gen_integer from
model_mommy.random_gen. This changed in October of 2016.

Point objects are now manually created for Report objects created in
tests.

TODO: Remove model_mommy too. Clean up tests.